# Generated by Django 5.1 on 2024-09-04 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickcommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickcommerce.coupon'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='exclude_categories',
            field=models.ManyToManyField(blank=True, related_name='excluded_category_coupons', to='quickcommerce.category'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='exclude_products',
            field=models.ManyToManyField(blank=True, related_name='excluded_coupons', to='quickcommerce.product'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='exclude_sale_items',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coupon',
            name='individual_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coupon',
            name='minimum_spend',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='specific_categories',
            field=models.ManyToManyField(blank=True, related_name='category_coupons', to='quickcommerce.category'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='specific_products',
            field=models.ManyToManyField(blank=True, related_name='coupons', to='quickcommerce.product'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='usage_limit_per_coupon',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='usage_limit_per_user',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='total_amount_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='quickcommerce.orderitem')),
            ],
        ),
    ]
