# Generated by Django 5.1 on 2024-09-04 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickcommerce', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='exclude_categories',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='exclude_products',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='exclude_sale_items',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='individual_use',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='minimum_spend',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='specific_categories',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='specific_products',
        ),
    ]
